name: Issue for this repository
on: issues
jobs: 
  notification_of_issue:
   runs-on: ubuntu-latest
   steps:
    - name: Event info
      run: echo "${{ toJSON(github.event) }}"
    - name: Event info, only the issue part
      run: echo "${{ toJSON(github.event.issue) }}"      