name: Issue for this repository
on: issues
jobs: 
  notification_of_issue:
   runs-on: ubuntu-latest
   steps:
    - name: Notify of the issue
      run: echo "${{ toJSON(github) }}"
    - name: Event info of the issue
      run: echo "${{ toJSON(github.event.issue) }}"      